import type { CreateDocumentRequestDto } from "@/types/dto";
import type { RequesterType } from "@/types/db";

export type CreateDocumentValidated = {
  ownerFullName: string;
  ownerIdentityNo: string;
  ownerBirthDate: Date;

  universityName: string;
  dormName: string | null;
  dormAddress: string | null;
  issueDate: Date;
  footerDatetime: Date;

  requesterType: RequesterType;
  companyId: string | null;
  directCustomerName: string | null;
  directCustomerPhone: string | null;

  priceAmount: number;
  priceCurrency: string;

  templateId: string | null;
  templateVersion: number | null;
  templateValues: Record<string, unknown> | null;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function parseDateOnly(input: string, fieldName: string): Date {
  const s = input.trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(s)) {
    throw Object.assign(
      new Error(`${fieldName} must be in YYYY-MM-DD format`),
      {
        status: 400,
      }
    );
  }

  const [y, m, d] = s.split("-").map((x) => Number(x));
  const dt = new Date(Date.UTC(y, m - 1, d));

  if (
    !Number.isFinite(y) ||
    !Number.isFinite(m) ||
    !Number.isFinite(d) ||
    dt.getUTCFullYear() !== y ||
    dt.getUTCMonth() !== m - 1 ||
    dt.getUTCDate() !== d
  ) {
    throw Object.assign(new Error(`${fieldName} is not a valid date`), {
      status: 400,
    });
  }
  return dt;
}

function parseDateTime(input: string, fieldName: string): Date {
  const s = input.trim();
  if (!s) {
    throw Object.assign(new Error(`${fieldName} is required`), { status: 400 });
  }

  // Support HTML datetime-local (no timezone) by treating it as local time.
  const dt = new Date(s);
  if (!Number.isFinite(dt.getTime())) {
    throw Object.assign(new Error(`${fieldName} must be a valid datetime`), {
      status: 400,
    });
  }
  return dt;
}

export function validateCreateDocumentBody(
  body: unknown
): CreateDocumentValidated {
  if (!isRecord(body)) {
    throw Object.assign(new Error("Invalid JSON body"), { status: 400 });
  }

  if ("token" in body || "barcode_id" in body || "reference_no" in body) {
    throw Object.assign(
      new Error(
        "token/barcode_id/reference_no must be generated by the server"
      ),
      { status: 400 }
    );
  }

  const ownerFullName =
    typeof body.owner_full_name === "string" ? body.owner_full_name.trim() : "";
  const ownerIdentityNo =
    typeof body.owner_identity_no === "string"
      ? body.owner_identity_no.trim()
      : "";
  const ownerBirthDateStr =
    typeof body.owner_birth_date === "string" ? body.owner_birth_date : "";

  if (!ownerFullName) {
    throw Object.assign(new Error("Owner name is required"), { status: 400 });
  }

  if (!ownerIdentityNo) {
    throw Object.assign(new Error("ID number must not be empty"), {
      status: 400,
    });
  }

  const ownerBirthDate = parseDateOnly(ownerBirthDateStr, "Date of birth");

  const universityName =
    typeof body.university_name === "string" ? body.university_name.trim() : "";
  if (!universityName) {
    throw Object.assign(new Error("University is required"), { status: 400 });
  }

  const dormNameRaw =
    typeof body.dorm_name === "string" ? body.dorm_name.trim() : "";
  const dormName = dormNameRaw ? dormNameRaw : null;

  const dormAddressRaw =
    typeof body.dorm_address === "string" ? body.dorm_address.trim() : "";
  const dormAddress = dormAddressRaw ? dormAddressRaw : null;

  const issueDateStr =
    typeof body.issue_date === "string" ? body.issue_date : "";
  const issueDate = parseDateOnly(issueDateStr, "Issue date");

  const footerDatetimeStr =
    typeof body.footer_datetime === "string" ? body.footer_datetime : "";
  const footerDatetime = parseDateTime(footerDatetimeStr, "Footer datetime");

  const requesterType = body.requester_type;
  if (requesterType !== "company" && requesterType !== "direct") {
    throw Object.assign(new Error("Requester type is invalid"), {
      status: 400,
    });
  }

  const companyIdRaw =
    typeof body.company_id === "string" ? body.company_id.trim() : "";
  const directCustomerNameRaw =
    typeof body.direct_customer_name === "string"
      ? body.direct_customer_name.trim()
      : "";
  const directCustomerPhoneRaw =
    typeof body.direct_customer_phone === "string"
      ? body.direct_customer_phone.trim()
      : "";

  const companyId = companyIdRaw ? companyIdRaw : null;
  const directCustomerName = directCustomerNameRaw
    ? directCustomerNameRaw
    : null;
  const directCustomerPhone = directCustomerPhoneRaw
    ? directCustomerPhoneRaw
    : null;

  if (requesterType === "company") {
    if (!companyId) {
      throw Object.assign(
        new Error("company_id is required for company requester"),
        {
          status: 400,
        }
      );
    }
  }
  if (requesterType === "direct") {
    if (!directCustomerName) {
      throw Object.assign(
        new Error("direct_customer_name is required for direct requester"),
        { status: 400 }
      );
    }
  }

  const priceAmount = Number((body as CreateDocumentRequestDto).price_amount);
  if (!Number.isFinite(priceAmount) || priceAmount < 0) {
    throw Object.assign(
      new Error("price_amount must be a non-negative number"),
      {
        status: 400,
      }
    );
  }

  const priceCurrency =
    typeof body.price_currency === "string" ? body.price_currency.trim() : "";
  if (!priceCurrency) {
    throw Object.assign(new Error("price_currency is required"), {
      status: 400,
    });
  }

  const templateIdRaw =
    typeof body.template_id === "string" ? body.template_id.trim() : "";
  const templateId = templateIdRaw ? templateIdRaw : null;

  const templateVersionRaw = (body as Record<string, unknown>).template_version;
  const templateVersion =
    typeof templateVersionRaw === "number" &&
    Number.isFinite(templateVersionRaw)
      ? Math.max(1, Math.floor(templateVersionRaw))
      : null;

  const templateValuesRaw = (body as Record<string, unknown>).template_values;
  const templateValues = isRecord(templateValuesRaw) ? templateValuesRaw : null;

  if (templateId && templateValues === null) {
    throw Object.assign(new Error("template_values must be an object"), {
      status: 400,
    });
  }

  return {
    ownerFullName,
    ownerIdentityNo,
    ownerBirthDate,
    universityName,
    dormName,
    dormAddress,
    issueDate,
    footerDatetime,
    requesterType,
    companyId,
    directCustomerName,
    directCustomerPhone,
    priceAmount,
    priceCurrency,

    templateId,
    templateVersion,
    templateValues,
  };
}
